version: '3.8'

services:
  gymadd:
    image: 6bf82afdbfbb
    container_name: gymadd
    ports:
      - "8088:8088"
    environment:
      - DB_HOST='mysql-programaciondis.alwaysdata.net
      - DB_USER=357676_bj
      - DB_PASSWORD=Uyt:tBHLgt4Kk_E
      - DB_NAME=programaciondis_gym
    networks:
      - gym-network

  gymlist:
    image: 9626aa8b1cf2
    container_name: gymlist
    ports:
      - "8089:8089"
    environment:
      - DB_HOST='mysql-programaciondis.alwaysdata.net
      - DB_USER=357676_bj
      - DB_PASSWORD=Uyt:tBHLgt4Kk_E
      - DB_NAME=programaciondis_gym
    networks:
      - gym-network

  gymupdate:
    image: ca36af4e3456
    container_name: gymupdate
    ports:
      - "8090:8090"
    environment:
      - DB_HOST='mysql-programaciondis.alwaysdata.net
      - DB_USER=357676_bj
      - DB_PASSWORD=Uyt:tBHLgt4Kk_E
      - DB_NAME=programaciondis_gym
    networks:
      - gym-network

  gymfrontend:
    image: 148f32ba6cdf
    container_name: gymfrontend
    ports:
      - "3003:3003"
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge
