name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t brayanbj27/bd-gym-frontend .
      - name: Publish image to docker hub
        run: docker push brayanbj27/bd-gym-frontend:latest   

  deploy: 
    needs: build
    runs-on: gym-front   
    steps:
      - name: Pull image from docker hub
        run: docker pull brayanbj27/bd-gym-frontend:latest
      - name: Delete Old Container
        run: docker rm -f gymContainer || true
      - name: Run docker container
        run: docker run -d --name gymContainer --network gym_network -p 3000:80 brayanbj27/bd-gym-frontend